server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/note
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp: use_jdbc_metadata_defaults = false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
